sudo: false

language: php
php:
  - 7.1
  - hhvm

services:
  - mysql

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - composer self-update && composer --version
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require squizlabs/php_codesniffer
  - composer install --prefer-dist

before_script:
  - mysql -e 'create database wordpress_test;'
  - cp .env.test .env
  - svn export --quiet https://develop.svn.wordpress.org/trunk/tests/phpunit/includes/ tests-includes

script:
  - phpcs --standard=ruleset.xml --extensions=php --ignore=web/wp/,vendor/,tests/,tests-includes/ -n -s .
  - phpunit

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master


