sudo: true

language: php
php:
  - 7.2

services:
  - mysql

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_install:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  # Unless we need XDebug, disable it for improved performance.
  - phpenv config-rm xdebug.ini || return 0

install:
  - composer self-update && composer --version
  - composer global require squizlabs/php_codesniffer
  - composer install --prefer-dist

matrix:
  include:
    - php: 7.2
      env: 
        WP_VERSION: latest
        SKIP_DB_CREATE: true

before_script:
  - mysql -e 'create database wordpress_test;'
  - cp .env.test .env
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION $SKIP_DB_CREATE
  - svn export --quiet https://develop.svn.wordpress.org/trunk/tests/phpunit/includes/ tests-includes

script:
  - ./vendor/bin/phpcs --standard=phpunit.ruleset.xml --extensions=php --ignore=web/wp/,vendor/,tests/,tests-includes/ -n -s .
  - phpunit

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master


